create database week7;
use week7;

-- 7.1
DROP TABLE IF EXISTS class;
CREATE TABLE class(id INT(5), Name CHAR(10));

INSERT INTO class VALUES (1,'one'),(2,'two');
SELECT * FROM class;

-- 7.2
START TRANSACTION;
INSERT INTO class VALUES (3,'THREE');
SAVEPOINT A;
INSERT INTO class VALUES (4,'FOUR');
SAVEPOINT B;
UPDATE class SET Name='RAJ' WHERE id=1;
SAVEPOINT C;
ROLLBACK TO SAVEPOINT A;
SELECT * FROM class;

-- 7.3
INSERT INTO class VALUES (5,'five');
COMMIT;
ROLLBACK TO SAVEPOINT B;
ROLLBACK TO SAVEPOINT C;
ROLLBACK TO SAVEPOINT A;
SELECT * FROM class;

-- TRY PROGRAM
START TRANSACTION;
INSERT INTO class VALUES (6,'six');
INSERT INTO class VALUES (7,'seven');
SELECT * FROM class;
COMMIT;
ROLLBACK;
SELECT * FROM class;
